http_helloworld_server:http_helloworld_server.cc tcp_thread_server.hpp tcp_socket.hpp
	g++ http_helloworld_server.cc -o http_helloworld_server -std=c++11 -lpthread

.PHONY:clean
clean:
	rm  http_helloworld_servert

